export const SET_HE_THONG_RAP_CHIEU = 'SET_HE_THONG_RAP_CHIEU';
export const SET_HE_THONG_PHIM_TRONG_RAP_CHIEU = 'SET_HE_THONG_PHIM_TRONG_RAP_CHIEU';
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM';
export const SET_DANH_SACH_TRONG_RAP_CHIEU= 'SET_DANH_SACH_TRONG_RAP_CHIEU';